name: CI

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  # this Action should follow steps to set up Python build environment
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Standard drop-in approach that should work for most people.
    - run: |
    	pwd
        ls -a
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /
    # ===============================
